// apps/desktop/src/pages/Calendar.tsx
import { useEffect, useState } from "react";
import { CalendarDays, Loader2, RefreshCw } from "lucide-react";
import { useTaskRepository } from "../data/TaskRepositoryContext";
import type { Task } from "../domain/tasks";

export default function Calendar() {
  const repository = useTaskRepository();
  const [tasks, setTasks] = useState<Task[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  async function load() {
    setLoading(true);
    setError(null);
    const start = new Date();
    start.setHours(0, 0, 0, 0);
    const end = new Date(start);
    end.setDate(end.getDate() + 6);
    end.setHours(23, 59, 59, 999);

    try {
      setTasks(await repository.listAgenda(start, end));
    } catch (e) {
      setError(String(e));
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    void load();
  }, []);

  return (
    <section className="page">
      <header className="page__head">
        <h1>Calendar</h1>
        <span className="page__sub">Next 7 days</span>
      </header>

      {loading && (
        <div className="card state">
          <Loader2 className="spin" size={18} aria-hidden="true" />
          <p>Loading agenda...</p>
        </div>
      )}
      {error && (
        <div className="card state state--error">
          <p>{error}</p>
          <button type="button" onClick={load}>
            <RefreshCw size={16} aria-hidden="true" />
            Retry
          </button>
        </div>
      )}
      {!loading && !error && tasks.length === 0 && (
        <div className="card empty">
          <CalendarDays size={20} aria-hidden="true" />
          <p>No scheduled tasks in the next 7 days.</p>
        </div>
      )}
      {!loading && !error && tasks.length > 0 && (
        <ol className="timeline">
          {tasks.map((task) => (
            <li key={task.id} className="timeline__item">
              <time>{formatAgendaDate(task.dueAt)}</time>
              <div>
                <b>{task.title}</b>
                {task.notes && <p>{task.notes}</p>}
              </div>
            </li>
          ))}
        </ol>
      )}
    </section>
  );
}

function formatAgendaDate(value: string | null) {
  if (!value) return "Unscheduled";
  return new Intl.DateTimeFormat(undefined, {
    weekday: "short",
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  }).format(new Date(value));
}

// apps/desktop/src/pages/Calendar.vue
<script setup lang="ts">
import { onMounted, ref } from "vue";
import { CalendarDays, Loader2, RefreshCw } from "lucide-vue-next";
import { useTaskRepository } from "../data/TaskRepositoryContext";
import type { Task } from "../domain/tasks";

const repository = useTaskRepository();
const tasks = ref<Task[]>([]);
const loading = ref(true);
const error = ref<string | null>(null);

onMounted(() => {
  void load();
});

async function load() {
  loading.value = true;
  error.value = null;
  const start = new Date();
  start.setHours(0, 0, 0, 0);
  const end = new Date(start);
  end.setDate(end.getDate() + 6);
  end.setHours(23, 59, 59, 999);

  try {
    tasks.value = await repository.listAgenda(start, end);
  } catch (e) {
    error.value = String(e);
  } finally {
    loading.value = false;
  }
}

function formatAgendaDate(value: string | null) {
  if (!value) return "Unscheduled";
  return new Intl.DateTimeFormat(undefined, {
    weekday: "short",
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  }).format(new Date(value));
}
</script>

<template>
  <section class="page">
    <header class="page__head">
      <h1>Calendar</h1>
      <span class="page__sub">Next 7 days</span>
    </header>

    <div v-if="loading" class="card state">
      <Loader2 class="spin" :size="18" aria-hidden="true" />
      <p>Loading agenda...</p>
    </div>
    <div v-if="error" class="card state state--error">
      <p>{{ error }}</p>
      <button type="button" @click="load">
        <RefreshCw :size="16" aria-hidden="true" />
        Retry
      </button>
    </div>
    <div v-if="!loading && !error && tasks.length === 0" class="card empty">
      <CalendarDays :size="20" aria-hidden="true" />
      <p>No scheduled tasks in the next 7 days.</p>
    </div>
    <ol v-if="!loading && !error && tasks.length > 0" class="timeline">
      <li v-for="task in tasks" :key="task.id" class="timeline__item">
        <time>{{ formatAgendaDate(task.dueAt) }}</time>
        <div>
          <b>{{ task.title }}</b>
          <p v-if="task.notes">{{ task.notes }}</p>
        </div>
      </li>
    </ol>
  </section>
</template>
