// apps/desktop/src/pages/Login.tsx
import { FormEvent, useState } from "react";
import { useNavigate } from "react-router-dom";

export default function Login() {
  const [email, setEmail] = useState("");
  const navigate = useNavigate();

  function onSubmit(e: FormEvent) {
    e.preventDefault();
    navigate("/today");
  }

  return (
    <div className="auth">
      <form className="auth__card" onSubmit={onSubmit}>
        <h1>Momo</h1>
        <p className="auth__hint">
          OIDC / Passkeys 登录链路待接入（BE-01）。当前为占位入口。
        </p>
        <label className="auth__label">
          Email
          <input
            type="email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            placeholder="you@example.com"
            required
          />
        </label>
        <button type="submit">Continue</button>
      </form>
    </div>
  );
}

// apps/desktop/src/pages/Login.vue
<script setup lang="ts">
import { ref } from "vue";
import { useRouter } from "vue-router";

const email = ref("");
const router = useRouter();

function onSubmit() {
  void router.push("/today");
}
</script>

<template>
  <div class="auth">
    <form class="auth__card" @submit.prevent="onSubmit">
      <h1>Momo</h1>
      <p class="auth__hint">
        OIDC / Passkeys 登录链路待接入（BE-01）。当前为占位入口。
      </p>
      <label class="auth__label">
        Email
        <input
          v-model="email"
          type="email"
          placeholder="you@example.com"
          required
        />
      </label>
      <button type="submit">Continue</button>
    </form>
  </div>
</template>
