// apps/desktop/src/pages/Today.vue
<script setup lang="ts">
import { onMounted, ref } from "vue";
import { Check, Loader2, Plus, RefreshCw } from "lucide-vue-next";
import { useTaskRepository } from "../data/TaskRepositoryContext";
import type { TodayTaskGroups } from "../domain/tasks";

const repository = useTaskRepository();
const groups = ref<TodayTaskGroups>({
  overdue: [],
  dueToday: [],
  completedToday: [],
});
const title = ref("");
const destination = ref<"today" | "inbox">("today");
const dueAtInput = ref("");
const estimateInput = ref("");
const loading = ref(true);
const saving = ref(false);
const error = ref<string | null>(null);

onMounted(() => {
  void load();
});

async function load() {
  loading.value = true;
  error.value = null;
  try {
    groups.value = await repository.listToday(new Date());
  } catch (e) {
    error.value = String(e);
  } finally {
    loading.value = false;
  }
}

async function onQuickAdd() {
  if (!title.value.trim()) return;
  saving.value = true;
  error.value = null;
  try {
    await repository.createTask({
      title: title.value,
      dueAt:
        destination.value === "today"
          ? dueAtInputToIso(dueAtInput.value) ?? defaultTodayDueAt()
          : null,
      estimateMin: estimateInputToNumber(estimateInput.value),
    });
    title.value = "";
    dueAtInput.value = "";
    estimateInput.value = "";
    await load();
  } catch (e) {
    error.value = String(e);
  } finally {
    saving.value = false;
  }
}

function dueAtInputToIso(value: string) {
  if (!value) return null;
  return new Date(value).toISOString();
}

function estimateInputToNumber(value: string) {
  const parsed = Number(value);
  return Number.isInteger(parsed) && parsed > 0 ? parsed : null;
}

function defaultTodayDueAt() {
  const due = new Date();
  due.setHours(12, 0, 0, 0);
  return due.toISOString();
}

function formatDateTime(value: string | null) {
  if (!value) return "No time";
  return new Intl.DateTimeFormat(undefined, {
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  }).format(new Date(value));
}
</script>

<template>
  <section class="page">
    <header class="page__head">
      <h1>Today</h1>
      <span class="page__sub">今日任务 · 逾期提醒 · 完成回看</span>
    </header>

    <form class="quick-add" @submit.prevent="onQuickAdd">
      <label class="sr-only" for="today-quick-add">Quick add task</label>
      <div class="row">
        <input
          id="today-quick-add"
          v-model="title"
          placeholder="Add a task for today"
        />
        <label class="sr-only" for="task-destination">Task destination</label>
        <select id="task-destination" v-model="destination">
          <option value="today">Today</option>
          <option value="inbox">Inbox</option>
        </select>
        <label class="sr-only" for="task-due-at">Task due date</label>
        <input
          id="task-due-at"
          v-model="dueAtInput"
          type="datetime-local"
          :disabled="destination === 'inbox'"
        />
        <label class="sr-only" for="task-estimate">Task estimate minutes</label>
        <input
          id="task-estimate"
          v-model="estimateInput"
          class="estimate-input"
          type="number"
          min="1"
          step="1"
          placeholder="min"
        />
        <button type="submit" :disabled="saving || !title.trim()">
          <Plus :size="16" aria-hidden="true" />
          {{ destination === "today" ? "Add for today" : "Add task" }}
        </button>
      </div>
    </form>

    <div v-if="loading" class="card state">
      <Loader2 class="spin" :size="18" aria-hidden="true" />
      <p>Loading local tasks...</p>
    </div>
    <div v-if="error" class="card state state--error">
      <p>{{ error }}</p>
      <button type="button" @click="load">
        <RefreshCw :size="16" aria-hidden="true" />
        Retry
      </button>
    </div>

    <div v-if="!loading && !error" class="task-grid">
      <section class="card task-section">
        <div class="section-title">
          <h2>Overdue</h2>
        </div>
        <p v-if="groups.overdue.length === 0" class="empty-text">Nothing here.</p>
        <ul v-else class="task-list">
          <li v-for="task in groups.overdue" :key="task.id" class="task-item">
            <span class="task-title is-danger">{{ task.title }}</span>
            <span class="task-meta">
              {{ formatDateTime(task.dueAt ?? task.completedAt) }}
            </span>
          </li>
        </ul>
      </section>

      <section class="card task-section">
        <div class="section-title">
          <h2>Due today</h2>
        </div>
        <p v-if="groups.dueToday.length === 0" class="empty-text">Nothing here.</p>
        <ul v-else class="task-list">
          <li v-for="task in groups.dueToday" :key="task.id" class="task-item">
            <span class="task-title">{{ task.title }}</span>
            <span class="task-meta">
              {{ formatDateTime(task.dueAt ?? task.completedAt) }}
            </span>
          </li>
        </ul>
      </section>

      <section class="card task-section">
        <div class="section-title">
          <h2>Completed today</h2>
          <Check :size="16" aria-hidden="true" />
        </div>
        <p v-if="groups.completedToday.length === 0" class="empty-text">
          Nothing here.
        </p>
        <ul v-else class="task-list">
          <li
            v-for="task in groups.completedToday"
            :key="task.id"
            class="task-item"
          >
            <span class="task-title">{{ task.title }}</span>
            <span class="task-meta">
              {{ formatDateTime(task.dueAt ?? task.completedAt) }}
            </span>
          </li>
        </ul>
      </section>
    </div>
  </section>
</template>

// apps/desktop/src/pages/Today.tsx
import { FormEvent, useEffect, useState, type ReactNode } from "react";
import { Check, Loader2, Plus, RefreshCw } from "lucide-react";
import { useTaskRepository } from "../data/TaskRepositoryContext";
import type { TodayTaskGroups } from "../domain/tasks";

export default function Today() {
  const repository = useTaskRepository();
  const [groups, setGroups] = useState<TodayTaskGroups>({
    overdue: [],
    dueToday: [],
    completedToday: [],
  });
  const [title, setTitle] = useState("");
  const [destination, setDestination] = useState<"today" | "inbox">("today");
  const [dueAtInput, setDueAtInput] = useState("");
  const [estimateInput, setEstimateInput] = useState("");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function load() {
    setLoading(true);
    setError(null);
    try {
      setGroups(await repository.listToday(new Date()));
    } catch (e) {
      setError(String(e));
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    void load();
  }, []);

  async function onQuickAdd(event: FormEvent) {
    event.preventDefault();
    if (!title.trim()) return;
    setSaving(true);
    setError(null);
    try {
      await repository.createTask({
        title,
        dueAt:
          destination === "today"
            ? dueAtInputToIso(dueAtInput) ?? defaultTodayDueAt()
            : null,
        estimateMin: estimateInputToNumber(estimateInput),
      });
      setTitle("");
      setDueAtInput("");
      setEstimateInput("");
      await load();
    } catch (e) {
      setError(String(e));
    } finally {
      setSaving(false);
    }
  }

  return (
    <section className="page">
      <header className="page__head">
        <h1>Today</h1>
        <span className="page__sub">今日任务 · 逾期提醒 · 完成回看</span>
      </header>

      <form className="quick-add" onSubmit={onQuickAdd}>
        <label className="sr-only" htmlFor="today-quick-add">
          Quick add task
        </label>
        <div className="row">
          <input
            id="today-quick-add"
            value={title}
            onChange={(event) => setTitle(event.target.value)}
            placeholder="Add a task for today"
          />
          <label className="sr-only" htmlFor="task-destination">
            Task destination
          </label>
          <select
            id="task-destination"
            value={destination}
            onChange={(event) =>
              setDestination(event.target.value === "inbox" ? "inbox" : "today")
            }
          >
            <option value="today">Today</option>
            <option value="inbox">Inbox</option>
          </select>
          <label className="sr-only" htmlFor="task-due-at">
            Task due date
          </label>
          <input
            id="task-due-at"
            type="datetime-local"
            value={dueAtInput}
            onChange={(event) => setDueAtInput(event.target.value)}
            disabled={destination === "inbox"}
          />
          <label className="sr-only" htmlFor="task-estimate">
            Task estimate minutes
          </label>
          <input
            id="task-estimate"
            className="estimate-input"
            type="number"
            min="1"
            step="1"
            value={estimateInput}
            onChange={(event) => setEstimateInput(event.target.value)}
            placeholder="min"
          />
          <button type="submit" disabled={saving || !title.trim()}>
            <Plus size={16} aria-hidden="true" />
            {destination === "today" ? "Add for today" : "Add task"}
          </button>
        </div>
      </form>

      {loading && <LoadingState />}
      {error && (
        <div className="card state state--error">
          <p>{error}</p>
          <button type="button" onClick={load}>
            <RefreshCw size={16} aria-hidden="true" />
            Retry
          </button>
        </div>
      )}

      {!loading && !error && (
        <div className="task-grid">
          <TaskSection title="Overdue" tasks={groups.overdue} tone="danger" />
          <TaskSection title="Due today" tasks={groups.dueToday} />
          <TaskSection
            title="Completed today"
            tasks={groups.completedToday}
            icon={<Check size={16} aria-hidden="true" />}
          />
        </div>
      )}
    </section>
  );
}

function dueAtInputToIso(value: string) {
  if (!value) return null;
  return new Date(value).toISOString();
}

function estimateInputToNumber(value: string) {
  const parsed = Number(value);
  return Number.isInteger(parsed) && parsed > 0 ? parsed : null;
}

function TaskSection({
  title,
  tasks,
  tone,
  icon,
}: {
  title: string;
  tasks: TodayTaskGroups[keyof TodayTaskGroups];
  tone?: "danger";
  icon?: ReactNode;
}) {
  return (
    <section className="card task-section">
      <div className="section-title">
        <h2>{title}</h2>
        {icon}
      </div>
      {tasks.length === 0 ? (
        <p className="empty-text">Nothing here.</p>
      ) : (
        <ul className="task-list">
          {tasks.map((task) => (
            <li key={task.id} className="task-item">
              <span className={tone === "danger" ? "task-title is-danger" : "task-title"}>
                {task.title}
              </span>
              <span className="task-meta">{formatDateTime(task.dueAt ?? task.completedAt)}</span>
            </li>
          ))}
        </ul>
      )}
    </section>
  );
}

function LoadingState() {
  return (
    <div className="card state">
      <Loader2 className="spin" size={18} aria-hidden="true" />
      <p>Loading local tasks...</p>
    </div>
  );
}

function defaultTodayDueAt() {
  const due = new Date();
  due.setHours(12, 0, 0, 0);
  return due.toISOString();
}

function formatDateTime(value: string | null) {
  if (!value) return "No time";
  return new Intl.DateTimeFormat(undefined, {
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  }).format(new Date(value));
}
