// apps/desktop/src/layouts/AppShell.vue
<script setup lang="ts">
import { ref } from "vue";
import { RouterLink, RouterView } from "vue-router";
import { PanelTopOpen } from "lucide-vue-next";
import { openWidgetWindow } from "../window/widgetWindow";

const nav = [
  { to: "/today", label: "Today" },
  { to: "/inbox", label: "Inbox" },
  { to: "/calendar", label: "Calendar" },
  { to: "/settings", label: "Settings" },
];

const widgetError = ref<string | null>(null);

async function onOpenWidget() {
  widgetError.value = null;
  try {
    await openWidgetWindow();
  } catch (e) {
    widgetError.value = String(e);
  }
}
</script>

<template>
  <div class="shell">
    <aside class="shell__sidebar">
      <div class="shell__brand">Momo</div>
      <nav class="shell__nav">
        <RouterLink
          v-for="item in nav"
          :key="item.to"
          :to="item.to"
          class="shell__nav-item"
          active-class="is-active"
        >
          {{ item.label }}
        </RouterLink>
      </nav>
      <div class="shell__footer">
        <button
          type="button"
          class="shell__widget-button"
          @click="onOpenWidget"
        >
          <PanelTopOpen :size="16" aria-hidden="true" />
          Open widget
        </button>
        <p v-if="widgetError" class="shell__error">{{ widgetError }}</p>
        <RouterLink to="/login" class="shell__nav-item">Sign out</RouterLink>
      </div>
    </aside>
    <main class="shell__main">
      <RouterView />
    </main>
  </div>
</template>

// apps/desktop/src/layouts/AppShell.tsx
import { NavLink, Outlet } from "react-router-dom";
import { PanelTopOpen } from "lucide-react";
import { useState } from "react";
import { openWidgetWindow } from "../window/widgetWindow";

const NAV = [
  { to: "/today", label: "Today" },
  { to: "/inbox", label: "Inbox" },
  { to: "/calendar", label: "Calendar" },
  { to: "/settings", label: "Settings" },
];

export default function AppShell() {
  const [widgetError, setWidgetError] = useState<string | null>(null);

  async function onOpenWidget() {
    setWidgetError(null);
    try {
      await openWidgetWindow();
    } catch (e) {
      setWidgetError(String(e));
    }
  }

  return (
    <div className="shell">
      <aside className="shell__sidebar">
        <div className="shell__brand">Momo</div>
        <nav className="shell__nav">
          {NAV.map((item) => (
            <NavLink
              key={item.to}
              to={item.to}
              className={({ isActive }) =>
                "shell__nav-item" + (isActive ? " is-active" : "")
              }
            >
              {item.label}
            </NavLink>
          ))}
        </nav>
        <div className="shell__footer">
          <button
            type="button"
            className="shell__widget-button"
            onClick={onOpenWidget}
          >
            <PanelTopOpen size={16} aria-hidden="true" />
            Open widget
          </button>
          {widgetError && <p className="shell__error">{widgetError}</p>}
          <NavLink to="/login" className="shell__nav-item">
            Sign out
          </NavLink>
        </div>
      </aside>
      <main className="shell__main">
        <Outlet />
      </main>
    </div>
  );
}
